---
- name: "Installing Apache Webserver"
  hosts: amazon
  become: true
  vars_files:
    - variables.yml
  tasks:
    
    - name: "Installing Apache Webserver"
      yum:
        name: httpd
        state: present
            
    - name: "Creating httpd.conf from httpd.conf.tmpl"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
        
            
    - name: "ReStarting/Enabling Service"
      service:
        name: httpd
        state: restarted
        enabled: true
